### ISSUE TITLE
Deprecation of JsonSchema

### ISSUE THREAD

**Issue by OssiGalkin** [CommunityHiQ/Frends.Community.ConvertXmlToCsv#2]
JsonSchema is going to be deprecated and it gives warning: "JSON Schema validation has been moved to its own package. See http://www.newtonsoft.com/jsonschema for more details."

New Json.NET Schema package (available http://www.newtonsoft.com/jsonschema) is not, however, under open source license.

**Comment by Svenskapojkarna** [comment]
Issue moved to https://github.com/CommunityHiQ/Frends.Community.Xml/issues/4
