### ISSUE TITLE
Content containing CSV separator

### ISSUE THREAD

**Issue by KRuusuv** [CommunityHiQ/Frends.Community.ConvertXmlToCsv#5]
If the the content of an XML element contains the separator, the task adds the character " to the beginning and the end of the value. For example, if the separator is ',', the value of <when>Not now, not ever</when> becomes "Not now, not ever". However, this does not have the intended result of producing a single CSV column value. If the separator is ',', the aforementioned result counts as two CSV column values: ""Not now" and "not ever"". 

It might be better that the task merely throws an error if one of the element values contains the separator. Then it would be up to the customer and developer to decide how to handle it.

**Comment by Svenskapojkarna** [comment]
Issue moved to https://github.com/CommunityHiQ/Frends.Community.Xml/issues/3
